// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjF2AcuQ5V4z-syVnCERhdJq8Rtuz6Fs8',
    appId: '1:36740258349:web:80d76026b9af96fcaab6a4',
    messagingSenderId: '36740258349',
    projectId: 'auth-learning-5c798',
    authDomain: 'auth-learning-5c798.firebaseapp.com',
    storageBucket: 'auth-learning-5c798.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhJY6TZfHR8FBN6Mh9l5RhmsZCBPvWOU0',
    appId: '1:36740258349:android:32ee42a1a8182d5faab6a4',
    messagingSenderId: '36740258349',
    projectId: 'auth-learning-5c798',
    storageBucket: 'auth-learning-5c798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaB-kV6gVF1gUv0WapzGxFRY8VqRSrAWE',
    appId: '1:36740258349:ios:0984341f4cb1d809aab6a4',
    messagingSenderId: '36740258349',
    projectId: 'auth-learning-5c798',
    storageBucket: 'auth-learning-5c798.firebasestorage.app',
    iosBundleId: 'com.example.loginLogout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaB-kV6gVF1gUv0WapzGxFRY8VqRSrAWE',
    appId: '1:36740258349:ios:0984341f4cb1d809aab6a4',
    messagingSenderId: '36740258349',
    projectId: 'auth-learning-5c798',
    storageBucket: 'auth-learning-5c798.firebasestorage.app',
    iosBundleId: 'com.example.loginLogout',
  );
}
